default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: evensteven_development

test: &test
  <<: *default
  database: evensteven_test

production:
  <<: *default
  database: evensteven_production
  username: evensteven
  password: <%= ENV['EVENSTEVEN_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
